# Generated by Django 5.2.8 on 2025-11-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendormanagement', '0002_vendor_service_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Service amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='expiry_date',
            field=models.DateField(help_text='Service expiry date', verbose_name='expiry date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='payment_due_date',
            field=models.DateField(help_text='Service payment due date', verbose_name='payment due date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(help_text='Service name', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vendormanagement.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(help_text='Vendor contact person', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Vendor creation date'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(help_text='Vendor email', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='Vendor name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(help_text='Vendor phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Vendor status', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Vendor last update date'),
        ),
    ]
