# Generated by Django 5.2.8 on 2025-11-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendormanagement', '0003_alter_service_amount_alter_service_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
